Repository WilhelmusLab/IceFloeTracker.jl, pull requests merged in 2023-06, with the labels that each got.

#297 Feat remove util scripts
  .gitignore
  Manifest.toml
  README.md
  Snakefile
  hpc/oscar-env.yaml
  hpc/snakemake-config.yaml
Labels: documentation, :broom: clean up

#301 fix: timedeltas as floats
  src/tracker/matchcorr.jl
  src/tracker/tracker.jl
  test/test-matchcorr.jl
Labels: bug

#306 fix: suppress kmeans output
  src/segmentation_a_direct.jl
Labels: :broom: clean up

#304 fix: println => @info
  src/segmentation_a_direct.jl
Labels: :broom: clean up

#309 fix: resolvecollisions!
  src/tracker/tracker-funcs.jl
Labels: bug

#311 docs: update MatchedPairs
  src/tracker/tracker-funcs.jl
Labels: documentation

#313 fix: update regionprops_table docstring example
  src/regionprops.jl
Labels: documentation
